CREATE OR REPLACE DATABASE AIRLINE_DWH;           -- Creating new database  

CREATE OR REPLACE SCHEMA AIRLINE_DWH.RAW;         -- For raw data 1-to-1
CREATE OR REPLACE SCHEMA AIRLINE_DWH.INTEGRATION; -- For cleaned data (L2)
CREATE OR REPLACE SCHEMA AIRLINE_DWH.ANALYTICS;   -- for marts & Secure Views (L3)
CREATE OR REPLACE SCHEMA AIRLINE_DWH.LOGGING;

CREATE OR REPLACE WAREHOUSE AIRLINE_WH 
WITH WAREHOUSE_SIZE = 'XSMALL' 
AUTO_SUSPEND = 60 
AUTO_RESUME = TRUE;

-- File format & Stage settings
USE SCHEMA AIRLINE_DWH.RAW;

-- File format object
CREATE OR REPLACE FILE FORMAT csv_format
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('', 'NULL');

-- Creating stage
CREATE OR REPLACE STAGE airline_stage
    FILE_FORMAT = csv_format;
