-- Table creation for raw data
CREATE OR REPLACE TABLE AIRLINE_DWH.RAW.AIRLINE_RAW_DATA (
    RAW_ID INT,
    PASSENGER_ID VARCHAR,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    GENDER VARCHAR,
    AGE INT,
    NATIONALITY VARCHAR,
    AIRPORT_NAME VARCHAR,
    AIRPORT_COUNTRY_CODE VARCHAR,
    COUNTRY_NAME VARCHAR,
    AIRPORT_CONTINENT VARCHAR,
    CONTINENTS VARCHAR,
    DEPARTURE_DATE VARCHAR, 
    ARRIVAL_AIRPORT VARCHAR,
    PILOT_NAME VARCHAR,
    FLIGHT_STATUS VARCHAR,
    TICKET_TYPE VARCHAR,
    PASSENGER_STATUS VARCHAR
);

-- Table for Airflow execution logging
CREATE OR REPLACE TABLE AIRLINE_DWH.LOGGING.AUDIT_LOG (
    LOG_ID INT AUTOINCREMENT,
    JOB_NAME VARCHAR,         
    TABLE_NAME VARCHAR,       
    ROWS_INSERTED INT,
    ROWS_UPDATED INT,
    EXECUTION_TIME TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    STATUS VARCHAR
);
