USE ROLE SECURITYADMIN;

-- Creating a role AIRFLOW_ROLE
CREATE OR REPLACE ROLE AIRFLOW_ROLE;

-- Define administrator's role
GRANT ROLE AIRFLOW_ROLE TO ROLE SYSADMIN;

USE ROLE ACCOUNTADMIN;

-- Warehouse rights (for Airflow)
GRANT USAGE ON WAREHOUSE AIRLINE_WH TO ROLE AIRFLOW_ROLE;

-- Database rights
GRANT USAGE ON DATABASE AIRLINE_DWH TO ROLE AIRFLOW_ROLE;

-- All schemas rights
GRANT ALL PRIVILEGES ON SCHEMA AIRLINE_DWH.RAW TO ROLE AIRFLOW_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA AIRLINE_DWH.INTEGRATION TO ROLE AIRFLOW_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA AIRLINE_DWH.ANALYTICS TO ROLE AIRFLOW_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA AIRLINE_DWH.LOGGING TO ROLE AIRFLOW_ROLE;

-- Rights on future tables in schemas
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA AIRLINE_DWH.RAW TO ROLE AIRFLOW_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA AIRLINE_DWH.INTEGRATION TO ROLE AIRFLOW_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA AIRLINE_DWH.ANALYTICS TO ROLE AIRFLOW_ROLE;
