-- Going to the INTEGRATION schema
USE SCHEMA AIRLINE_DWH.INTEGRATION;

-- 1. Passengers table
CREATE OR REPLACE TABLE DIM_PASSENGERS (
    PASSENGER_PK INT AUTOINCREMENT,
    PASSENGER_ID VARCHAR,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    GENDER VARCHAR,
    AGE INT,
    NATIONALITY VARCHAR,
    LOAD_TIME TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 2. Airports table
CREATE OR REPLACE TABLE DIM_AIRPORTS (
    AIRPORT_PK INT AUTOINCREMENT,
    AIRPORT_NAME VARCHAR,
    COUNTRY_CODE VARCHAR,
    COUNTRY_NAME VARCHAR,
    CONTINENT VARCHAR,
    LOAD_TIME TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 3. Facts table (Flights)
CREATE OR REPLACE TABLE FACT_FLIGHTS (
    FLIGHT_PK INT AUTOINCREMENT,
    PASSENGER_ID VARCHAR,
    AIRPORT_NAME VARCHAR,
    DEPARTURE_DATE DATE, 
    ARRIVAL_AIRPORT VARCHAR,
    PILOT_NAME VARCHAR,
    FLIGHT_STATUS VARCHAR,
    TICKET_TYPE VARCHAR,
    LOAD_TIME TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Analytical layer creation (Layer 3)
USE SCHEMA AIRLINE_DWH.ANALYTICS;

-- Mart for report
CREATE OR REPLACE TABLE FLIGHT_ANALYTICS_MART (
    AIRPORT_NAME VARCHAR,
    TOTAL_FLIGHTS INT,
    AVG_PASSENGER_AGE FLOAT,
    REPORT_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
