-- Main Procedure 
CREATE OR REPLACE PROCEDURE AIRLINE_DWH.INTEGRATION.SP_TRANSFORM_AIRLINE_DATA()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
BEGIN
    -- 1. Full tables cleaning
    TRUNCATE TABLE AIRLINE_DWH.INTEGRATION.DIM_PASSENGERS;
    TRUNCATE TABLE AIRLINE_DWH.INTEGRATION.DIM_AIRPORTS;
    TRUNCATE TABLE AIRLINE_DWH.INTEGRATION.FACT_FLIGHTS;
    TRUNCATE TABLE AIRLINE_DWH.ANALYTICS.FLIGHT_ANALYTICS_MART;

    -- 2. Load L2 lvl (Integrationala layer)
    INSERT INTO AIRLINE_DWH.INTEGRATION.DIM_PASSENGERS (PASSENGER_ID, FIRST_NAME, LAST_NAME, GENDER, AGE, NATIONALITY)
    SELECT DISTINCT PASSENGER_ID, FIRST_NAME, LAST_NAME, GENDER, AGE, NATIONALITY
    FROM AIRLINE_DWH.RAW.AIRLINE_RAW_DATA;

    INSERT INTO AIRLINE_DWH.INTEGRATION.DIM_AIRPORTS (AIRPORT_NAME, COUNTRY_CODE, COUNTRY_NAME, CONTINENT)
    SELECT DISTINCT AIRPORT_NAME, AIRPORT_COUNTRY_CODE, COUNTRY_NAME, CONTINENTS
    FROM AIRLINE_DWH.RAW.AIRLINE_RAW_DATA;

    INSERT INTO AIRLINE_DWH.INTEGRATION.FACT_FLIGHTS (PASSENGER_ID, AIRPORT_NAME, DEPARTURE_DATE, ARRIVAL_AIRPORT, PILOT_NAME, FLIGHT_STATUS, TICKET_TYPE)
    SELECT 
        PASSENGER_ID, AIRPORT_NAME, TO_DATE(DEPARTURE_DATE, 'MM/DD/YYYY'),
        ARRIVAL_AIRPORT, PILOT_NAME, FLIGHT_STATUS, TICKET_TYPE
    FROM AIRLINE_DWH.RAW.AIRLINE_RAW_DATA;

    -- 3. Completion L3 (Analytical layer / Mart)
    -- Taking data from the tables DIM & FACT
    INSERT INTO AIRLINE_DWH.ANALYTICS.FLIGHT_ANALYTICS_MART (AIRPORT_NAME, TOTAL_FLIGHTS, AVG_PASSENGER_AGE)
    SELECT 
        f.AIRPORT_NAME, 
        COUNT(f.FLIGHT_PK), 
        AVG(p.AGE)
    FROM AIRLINE_DWH.INTEGRATION.FACT_FLIGHTS f
    JOIN AIRLINE_DWH.INTEGRATION.DIM_PASSENGERS p ON f.PASSENGER_ID = p.PASSENGER_ID
    GROUP BY f.AIRPORT_NAME;

    -- 4. LOGGING
    INSERT INTO AIRLINE_DWH.LOGGING.AUDIT_LOG (JOB_NAME, TABLE_NAME, ROWS_INSERTED, STATUS)
    VALUES ('AIRLINE_MAIN_PIPELINE', 'L2_AND_L3_LAYERS', 1, 'SUCCESS');

    RETURN 'Success: Integration and Analytics layers reloaded';
END;
$$;
